In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [17]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [18]:
data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [19]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [20]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [21]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [22]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
## Save the encoders and scaler
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender,f)
with open('one_hot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo,f)
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

ANN REGRESSION PROBLEM STATEMENT

In [26]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),  
    Dense(1)
])

model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

WARNING:tensorflow:From d:\Python\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From d:\Python\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [32]:
## Set up the Tensorboar
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [33]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [34]:
history = model.fit(
    X_train,y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorflow_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 6ms/step - loss: 51073.5391 - mae: 51073.5391 - val_loss: 50554.5312 - val_mae: 50554.5312
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 51239.7734 - mae: 51239.7734 - val_loss: 50316.3516 - val_mae: 50316.3516
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 51156.2461 - mae: 51156.2461 - val_loss: 50358.5312 - val_mae: 50358.5312
Epoch 4/100
250/250 [==============================] - 1s 6ms/step - loss: 51005.7461 - mae: 51005.7461 - val_loss: 50507.6836 - val_mae: 50507.6836
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 51076.4883 - mae: 51076.4883 - val_loss: 50302.1250 - val_mae: 50302.1250
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 50905.8203 - mae: 50905.8203 - val_loss: 50296.8125 - val_mae: 50296.8125
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 50888.1055 - mae: 50888.1055 - val_loss: 51486.5938 - val_mae: 51486.5938
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 51106.7070 - mae: 51106.7070 - val_loss: 51597.1562 - val_mae: 51597.1562
Epoch 9/100
250/250 [==============================] - 2s 6ms/step - loss: 50974.5234 - mae: 50974.5234 - val_loss: 50405.8672 - val_mae: 50405.8672
Epoch 10/100
250/250 [==============================] - 1s 6ms/step - loss: 51039.8086 - mae: 51039.8086 - val_loss: 50308.9922 - val_mae: 50308.9922
Epoch 11/100
250/250 [==============================] - 1s 6ms/step - loss: 50873.6094 - mae: 50873.6094 - val_loss: 50809.1562 - val_mae: 50809.1562
Epoch 12/100
250/250 [==============================] - 1s 6ms/step - loss: 51004.4805 - mae: 51004.4805 - val_loss: 50584.4570 - val_mae: 50584.4570
Epoch 13/100
250/250 [==============================] - 1s 6ms/step - loss: 50929.1875 - mae: 50929.1875 - val_loss: 50354.3242 - val_mae: 50354.3242
Epoch 14/100
250/250 [==============================] - 1s 6ms/step - loss: 51001.6250 - mae: 51001.6250 - val_loss: 50657.1680 - val_mae: 50657.1680
Epoch 15/100
250/250 [==============================] - 2s 6ms/step - loss: 50963.0078 - mae: 50963.0078 - val_loss: 50290.8203 - val_mae: 50290.8203
Epoch 16/100
250/250 [==============================] - 1s 6ms/step - loss: 50880.3672 - mae: 50880.3672 - val_loss: 50370.4336 - val_mae: 50370.4336
Epoch 17/100
250/250 [==============================] - 1s 6ms/step - loss: 50997.1992 - mae: 50997.1992 - val_loss: 50729.6562 - val_mae: 50729.6562
Epoch 18/100
250/250 [==============================] - 1s 6ms/step - loss: 51027.6836 - mae: 51027.6836 - val_loss: 50452.6680 - val_mae: 50452.6680
Epoch 19/100
250/250 [==============================] - 1s 6ms/step - loss: 50922.7969 - mae: 50922.7969 - val_loss: 50461.3281 - val_mae: 50461.3281
Epoch 20/100
250/250 [==============================] - 1s 6ms/step - loss: 50984.8945 - mae: 50984.8945 - val_loss: 50513.7734 - val_mae: 50513.7734
Epoch 21/100
250/250 [==============================] - 1s 6ms/step - loss: 50894.9453 - mae: 50894.9453 - val_loss: 50985.8086 - val_mae: 50985.8086
Epoch 22/100
250/250 [==============================] - 1s 6ms/step - loss: 51047.2461 - mae: 51047.2461 - val_loss: 50323.3633 - val_mae: 50323.3633
Epoch 23/100
250/250 [==============================] - 2s 6ms/step - loss: 50893.7148 - mae: 50893.7148 - val_loss: 50431.9961 - val_mae: 50431.9961
Epoch 24/100
250/250 [==============================] - 2s 6ms/step - loss: 50799.8672 - mae: 50799.8672 - val_loss: 50463.7734 - val_mae: 50463.7734
Epoch 25/100
250/250 [==============================] - 1s 6ms/step - loss: 50812.4453 - mae: 50812.4453 - val_loss: 50661.5781 - val_mae: 50661.5781

In [35]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [37]:
%tensorboard --logdir regressionlogs/fit/

In [38]:
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 [==============================] - 0s 3ms/step - loss: 50290.8203 - mae: 50290.8203
Test MAE: 50290.8203125

In [39]:
model.save('regression_model.h5')

d:\Python\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(